### ISSUE TITLE
Why elmo fine-tuning experiments are not listed in the original paper?

### ISSUE THREAD

**Issue by izuna385** [Andy-jqa/probing_biomed_embeddings#1]
Thanks for uploading codes and publishing paper! I'm very interested in your paper.

My naive question is , why experiment of elmo fine-tuning is not listed in the original paper.
Simply integrating elmo into NER(or another task) model, like
```
options_file = "options.json"
weight_file = "weights.hdf5"
elmo = Elmo(options_file, weight_file, 2, dropout=0)
```
and fine-tuning weight including elmo layer during training is one idea. 

My understanding is that, for encoding sequence/sentence with fixing elmo-feature, precache process exists.

BioBert fine-tuning experiments are written, but I'd like to know why fine-tuning with elmo is not listed.
Thanks.

**Comment by izuna385** [comment]
Sorry for my misunderstandings.
It seems that "Whole" setting includes fine-tunings, so I close this issue.

**Comment by drqiaojin** [comment]
> Sorry for my misunderstandings.
> It seems that "Whole" setting includes fine-tunings, so I close this issue.

Hi @izuna385,

This is a good question, and actually the "Whole" setting still doesn't fine-tune ELMo. The "Whole" setting is designed to compare the pre-trained contextual embeddings **the way they are supposed to be used**, which means fine-tuning for BERT and fixed feature-extractor for ELMo. (For fine-tuning ELMo, [this paper](https://arxiv.org/pdf/1903.05987.pdf) might be interesting to read.)

A basic assumption of our probing tasks is that learning **universal** representations of words is an important long-term goal of NLP, so fine-tuning ELMo is beyond the scope of this work.

Thanks for your interests!
Qiao

**Comment by izuna385** [comment]
> learning universal representations of words is an important long-term goal of NLP, so fine-tuning ELMo is beyond the scope of this work. 

So the paper follows how ELMo/BERT get contextual embeddings. Clear purpose, and now I think I get point.
Again, thanks for your paper and relply!
